[supabase]
supabase_url = "https://ukapgwhimdtxcclwsjia.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrYXBnd2hpbWR0eGNjbHdzamlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MjQ4NzYsImV4cCI6MjA3MTUwMDg3Nn0.yWQA9xWNPYB2igo4f8QR2fs30zuqiC3pHnKje0USyZg"
